version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ptbox-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend